// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzDRkq_Et3tZIyLdTU-e_PeT9x9FlZGYI',
    appId: '1:241705388194:web:b5efe4a9ef4b71c81c6ffb',
    messagingSenderId: '241705388194',
    projectId: 'news-app-5a982',
    authDomain: 'news-app-5a982.firebaseapp.com',
    storageBucket: 'news-app-5a982.appspot.com',
    measurementId: 'G-7KBR9E6BNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4wcrPG517TtaFVQ2WhMo8kdNXhPXpt0',
    appId: '1:241705388194:android:3d3d2a9c772b8f351c6ffb',
    messagingSenderId: '241705388194',
    projectId: 'news-app-5a982',
    storageBucket: 'news-app-5a982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_dsQS4OTrpcVjWHu_HKtV7qnMf7qsrw',
    appId: '1:241705388194:ios:a8c948f4ba7a50991c6ffb',
    messagingSenderId: '241705388194',
    projectId: 'news-app-5a982',
    storageBucket: 'news-app-5a982.appspot.com',
    iosClientId:
        '241705388194-eksgrefuj24hmeam9h666aajtq9ap9bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR_dsQS4OTrpcVjWHu_HKtV7qnMf7qsrw',
    appId: '1:241705388194:ios:5942309132bccce81c6ffb',
    messagingSenderId: '241705388194',
    projectId: 'news-app-5a982',
    storageBucket: 'news-app-5a982.appspot.com',
    iosClientId:
        '241705388194-121q3tvhajgt3oitk0r0uv3tcrhlp379.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
